name: Lotims
favicon: null
layout_spectrum: 0.9322675685398281
typography_spectrum: 0.29820177401416004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#114755'
    - '#52fdfe'
    - '#277caa'
    - '#37a1dc'
    - '#45c0fc'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
