name: Lotims
favicon: null
layout_spectrum: 0.9322675685398281
typography_spectrum: 0.29820177401416004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.22807144583202899
  lightness: 0.4782662186771631
  saturation: 0.9896395485848188
  rhythmicContrast: 0.9466621752362698
purpose: []
